In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import pandas as pd
import numpy as np
from sklearn import cross_validation as cv
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor


In [3]:
df = pd.read_csv("./../spam.train.txt", delim_whitespace=True, header=None)
x_data = df.ix[:, 1:]; y_data = df.ix[:, 0]

x_train, x_test, y_train, y_test = cv.train_test_split(x_data.as_matrix(), y_data.as_matrix(),
                                                       test_size=0.25, random_state=288)

In [4]:
print x_train.shape

(5319, 102)


In [6]:
from model_tree import best_split_mse, build_tree, tree_predict_one, tree_predict, best_split_mse_brute_force, best_split_lin_reg

In [11]:
def best_split_test1():
    a = np.array([6,5,4,5,6,7,4,3,17,12,15,14,16,19,17])
    b = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1,1])
    _,_,val,_ = best_split_mse(a, b)
    assert(val == 12)
best_split_test1()

In [14]:
def best_split_test2():
    a = np.array([6,5,4,5,6,7,4,3,17,12,15,14,16,19,17])
    b = np.array([10,39,20,40,30,20,10,30,154,167,187,154,167,187,143])
    print best_split_mse(a, b)
    _,_,val,_ = best_split_mse(a, b)
    assert(val == 12)
best_split_test2()

(array([7, 2, 6, 1, 3, 0, 4, 5]), array([ 9, 11, 10, 12,  8, 14, 13]), 12, 14354.800079365081)


In [26]:
def build_tree_test1(min_samples_leaf=1):
    f1 = np.array([6,5,4,5,6,7,4,3,17,12,15,14,16,19,17])
    f2 = np.array([6,5,4,5,6,7,34,20,17,12,15,14,16,19,17])
    y = np.array([0,0,0,0,0,0,0,0,1, 1, 1, 1, 1, 1, 1])
    x = np.vstack((f1,f2)).T
    tree = build_tree(x, y, min_samples_leaf=min_samples_leaf)
    return tree

build_tree_test1();

In [27]:
def tree_predict_test1():
    tree = build_tree_test1(1)

    return tree_predict_one([3,3], tree)
tree_predict_test1()

0.0

In [28]:
def tree_test_on_data(x_train, x_test, y_train, y_test):
    tree = build_tree(x_train, y_train, min_samples_leaf=4, max_depth=6)
    y_pred = tree_predict(x_test, tree)
    
    print mean_squared_error(y_test, y_pred)
    
tree_test_on_data(x_train, x_test, y_train, y_test)

KeyboardInterrupt: 

In [ ]:
t.fb.y

In [29]:
def test_sklearn_tree(x_train, x_test, y_train, y_test):
    dtr = DecisionTreeRegressor(min_samples_leaf=3)
    dtr.fit(x_train, y_train)
    y_pred = dtr.predict(x_test)
    print mean_squared_error(y_test, y_pred)
%timeit test_sklearn_tree(x_train, x_test, y_train, y_test)

0.0624636728047
0.0650068896405
0.0634773894526
0.0630574345484
1 loops, best of 3: 348 ms per loop


In [55]:
def test_best_split_mse_brute_force():
    x = np.array([6,5,4,5,6,7,4,3,17,12,15,14,16,19,17])
    y = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1,1])
    i1,i2,val,_ = best_split_mse_brute_force(x, y)
    print val
    print y[i1]
    print y[i2]
    assert(val == 12)
    
test_best_split_mse_brute_force()

12
[0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1]


In [67]:
def test_best_split_lin_reg():
    x = np.array([6,5,4,5,6,7,4,3,17,12,15,14,16,19,17])
    y = np.array([0,0,0,0,0,0,0,0,1,1,1,1,1,1,1])
    
    print best_split_lin_reg(x, y)
test_best_split_lin_reg()

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

In [39]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])